name       : intel-microcode
version    : 2018.01.08
release    : 3
source     :
    - https://downloadmirror.intel.com/27431/eng/microcode-20180108.tgz : 063f1aa3a546cb49323a5e0b516894e4b040007107b8c8ff017aca8a86204130
license    : EULA
component  : system.boot
summary    : The microcode data file contains the latest Linux microcode definitions for all Intel® Processors
description: |
    The microcode data file contains the latest Linux microcode definitions for all Intel® Processors. Users will generally not need to install this package as early microcode updating is already enabled in the kernel.
install    : |
    install -dm755 $installdir/lib/firmware/intel-ucode/
    cp -v intel-ucode/* $installdir/lib/firmware/intel-ucode/
