name       : intel-microcode
version    : 2018.08.07
release    : 8
source     :
    - https://downloadmirror.intel.com/28039/eng/microcode-20180807.tgz : 29f9e8dc27e6c9b6488cecd7fe2394030307799e511db2d197d9e6553a7f9e40
license    : EULA
component  : system.boot
summary    : The microcode data file contains the latest Linux microcode definitions for all Intel® Processors
description: |
    The microcode data file contains the latest Linux microcode definitions for all Intel® Processors. Users will generally not need to install this package as early microcode updating is already enabled in the kernel.
install    : |
    # dracut will choke otherwise
    rm -f intel-ucode/list

    install -Dm00644 intel-ucode/* -t $installdir/lib/firmware/intel-ucode/
