name       : intel-microcode
version    : 2018.03.12
release    : 5
source     :
    - https://downloadmirror.intel.com/27591/eng/microcode-20180312.tgz : 0b381face2df1b0a829dc4fa8fa93f47f39e11b1c9c22ebd44f8614657c1e779
license    : EULA
component  : system.boot
summary    : The microcode data file contains the latest Linux microcode definitions for all Intel® Processors
description: |
    The microcode data file contains the latest Linux microcode definitions for all Intel® Processors. Users will generally not need to install this package as early microcode updating is already enabled in the kernel.
install    : |
    install -dm755 $installdir/lib/firmware/intel-ucode/
    cp -v intel-ucode/* $installdir/lib/firmware/intel-ucode/
